name: KMM Tests

on:
  pull_request:
    branches: [ main ]

permissions:
  checks: write
  pull-requests: write

jobs:
  build:

    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Check BridgeClient
      env:
        testExternalId01: ${{ secrets.TEST_EXTERNAL_ID_01 }}
      run: ./gradlew check
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action/composite@v1
      if: always()
      with:
        files: bridge-client/build/test-results/**/*.xml
    - name: Upload Reports
      uses: actions/upload-artifact@v2
      with:
        name: Test-Reports
        path: assessmentmodel-sdk/build/reports
      if: always()
