name: Build CI

on:
  push:
    branches: [ adding-tests ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Check BridgeClient
      env:
        testExternalId01: ${{ secrets.TEST_EXTERNAL_ID_01 }}
      run: ./gradlew check
